import { Upload, FileText, Image, ChevronRight } from "lucide-react";
import { jsPDF } from "jspdf";

interface ExportPanelProps {
  caseId: string;
  patientId: string;
  date: string;
  confidenceScore: number;
  detections: { name: string; confidence: number }[];
  polypDetected: boolean;
}

export function ExportPanel({
  caseId,
  patientId,
  date,
  confidenceScore,
  detections,
  polypDetected,
}: ExportPanelProps) {
  const generatePDFReport = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageWidth, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("PolypNet AI", 20, 25);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Medical Imaging Analysis Report", 20, 33);

    // Case Information
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Case Information", 20, 55);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Case ID: ${caseId}`, 20, 65);
    doc.text(`Patient ID: ${patientId}`, 20, 72);
    doc.text(`Analysis Date: ${date}`, 20, 79);
    doc.text(`Report Generated: ${new Date().toLocaleString()}`, 20, 86);

    // Analysis Results
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Analysis Results", 20, 100);

    // Status Badge
    if (polypDetected) {
      doc.setFillColor(239, 68, 68);
      doc.roundedRect(20, 105, 50, 10, 2, 2, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text("POLYP DETECTED", 25, 112);
    } else {
      doc.setFillColor(34, 197, 94);
      doc.roundedRect(20, 105, 40, 10, 2, 2, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text("NO POLYP", 27, 112);
    }

    // Confidence Score
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Overall Confidence Score: ${(confidenceScore * 100).toFixed(1)}%`, 20, 125);

    // Detection Details
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Detection Details", 20, 140);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    let yPos = 150;
    detections.forEach((detection, index) => {
      doc.text(`${index + 1}. ${detection.name}: ${(detection.confidence * 100).toFixed(2)}%`, 25, yPos);
      yPos += 8;
    });

    // Footer
    doc.setFillColor(241, 245, 249);
    doc.rect(0, 270, pageWidth, 27, "F");

    doc.setTextColor(100, 116, 139);
    doc.setFontSize(8);
    doc.text("This report is generated by PolypNet AI v2.4 (YOLOv8)", 20, 280);
    doc.text("For clinical use only. Please consult with a qualified medical professional.", 20, 287);

    // Save the PDF
    doc.save(`PolypNet_Report_${caseId}_${new Date().toISOString().split("T")[0]}.pdf`);
  };

  const handleExportMask = () => {
    // Placeholder for mask export functionality
    alert("Mask export feature coming soon!");
  };

  return (
    <div className="mx-4 md:mx-8 mb-6 bg-card rounded-xl border border-border overflow-hidden animate-fade-in">
      {/* Header */}
      <div className="bg-panel-header px-4 md:px-6 py-4 border-b border-border">
        <h3 className="text-foreground font-semibold flex items-center gap-2">
          <Upload className="w-5 h-5 text-primary" />
          Export Analysis
        </h3>
      </div>

      {/* Export Options */}
      <div className="p-4 grid grid-cols-1 sm:grid-cols-2 gap-3">
        {/* Download Report */}
        <button
          onClick={generatePDFReport}
          className="bg-panel-header hover:bg-secondary border border-border hover:border-primary rounded-lg p-4 transition-all group text-left"
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-detection-high/20 rounded-lg flex items-center justify-center">
                <FileText className="w-6 h-6 text-detection-high" />
              </div>
              <div>
                <div className="text-foreground font-semibold mb-1">Download Report</div>
                <div className="text-muted-foreground text-sm">PDF • 2.4 MB</div>
              </div>
            </div>
            <ChevronRight className="w-5 h-5 text-muted-foreground group-hover:text-primary transition" />
          </div>
        </button>

        {/* Export Mask */}
        <button
          onClick={handleExportMask}
          className="bg-panel-header hover:bg-secondary border border-border hover:border-primary rounded-lg p-4 transition-all group text-left"
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-success/20 rounded-lg flex items-center justify-center">
                <Image className="w-6 h-6 text-success" />
              </div>
              <div>
                <div className="text-foreground font-semibold mb-1">Export Mask</div>
                <div className="text-muted-foreground text-sm">PNG • HIGH RES</div>
              </div>
            </div>
            <ChevronRight className="w-5 h-5 text-muted-foreground group-hover:text-primary transition" />
          </div>
        </button>
      </div>
    </div>
  );
}
